version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - app-net

  service1:
    build: ./service1
    expose:
      - "8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      retries: 3
    networks:
      - app-net

  service2:
    build: ./service2
    expose:
      - "8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      retries: 3
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
